# Generated by Django 5.0.2 on 2024-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.TextField()),
                ('receipe_description', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
