# Generated by Django 5.0.2 on 2024-04-23 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_receipe_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receipe',
            new_name='recipe',
        ),
    ]
