# Generated by Django 5.0.2 on 2024-04-30 19:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0014_rename_receipe_description_recipe_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='images/'),
        ),
    ]
